### ISSUE TITLE
[improvement idea] zoom per page

### ISSUE THREAD

**Issue by MZorzy** [TrakHound/TrakHound-Community#34]
hi
maybe can be usefull save zoom setting per page.
so can set&save overview at 50% , OEE status at 95% , Production at 115% 
and menu with other (fixed) zoom for all page.
so swich from a view to other as ever the best size view.

**Comment by PatrickRitchie** [comment]
This should already be implemented in the latest versions (> 1.5.0) but let me know if it doesn't work the way you are suggesting it should.

Thanks,

-Patrick

**Comment by MZorzy** [comment]
i'm on 1.5.4
when full screen "+" and "-" change zoom of all page and do not save by page

**Comment by MZorzy** [comment]
closed, due waiting dasboard 2.0
