### ISSUE TITLE
[question] what's new on v1.5.5 ?

### ISSUE THREAD

**Issue by MZorzy** [TrakHound/TrakHound-Community#36]
hi
on site there is DL of v1.5.5, what's new? here v1.5.1

**Comment by PatrickRitchie** [comment]
Mostly changes under the hood.

- Added the ability to use the LocalServer on IPs other than just the localhost
- Fixed a few bugs with the Dashboard and Server
- Added the use of the NLog logging file
- Updated to use new MTConnect.NET library (>v2.0)
- Updated to use new TrakHound.com domains

**Comment by MZorzy** [comment]
tnx
