### ISSUE TITLE
Can't connet to Fanuc-MTConnect-Agent ?

### ISSUE THREAD

**Issue by MZorzy** [TrakHound/TrakHound-Community#38]
Hi
i have installed Fanuc-MTConnect-Agent , setup it, and now i have a running fanuc agent on port 7878
i see true real data with firefox on 127.0.0.1:7878 , but can't add to TrakHound-Community
's DeviceManager .

auto scanned port 7878,8193,5000+
scanned 127.0.0.1 and ip of the real machine (fanuc 30i) ... nothing :-(

can add and see Okuma demo

**Comment by MZorzy** [comment]
have a page on :5000 aùwhere see a 'dummy' , but nothing orher relater to my 30i.
but see correct data (program number, counter etcetc) on 127.0.0.1:7878

**Comment by PatrickRitchie** [comment]
@MZorzy Whenever you add a new Adapter, it should update the devices.xml file for the Agent as well. Have you tried restarting the Agent to make sure the updated devices.xml file is read?

**Comment by MZorzy** [comment]
C:\Program Files (x86)\Fanuc MTConnect Agent\Agent\bin\agent.cfg
last lines
 `Adapters {

Fanuc-30i-01 {
Port = 7878
}

Fanuc-30i-02 {
Port = 7879
}`

on C:\Program Files (x86)\Fanuc MTConnect Agent\Adapters the 2 dir
`Fanuc-30i-01
Fanuc-30i-02 `

but on C:\Program Files (x86)\Fanuc MTConnect Agent\Agent\bin\devices.xml
`<?xml version="1.0" encoding="utf-8"?>
<MTConnectDevices>
  <Header creationTime="2011-04-26T19:41:27Z" instanceId="1303739716" bufferSize="131072" version="1.1" />
  <Devices>
    <Device id="dummy" name="dummy" uuid="dummy">
	  
	</Device>
  </Devices>
</MTConnectDevices>`

community 1.5.7 & Adapter 1.1 from site, win7sp1 full upgraded.
