### ISSUE TITLE
Trackhound server stopped and wont start

### ISSUE THREAD

**Issue by skibum1869** [TrakHound/TrakHound-Community#47]
The server is stopping, and wont come up after a reboot on windows 10.

``` cmd
C:\Program Files (x86)\TrakHound\Server>TrakHound-Server.exe
--------------------------------------------------
  _______ _    _
 |__   __| |  | |  TrakHound Server
    | |  | |__| |  v1.5.9.23220
    | |  |  __  |
    | |  | |  | |  GPLv3
    |_|  |_|  |_|  Copyright TrakHound Inc. 2017

  Open Source CNC Data Acquistion Software
          Package using MTConnect
             www.TrakHound.com
--------------------------------------------------
TrakHound Data API Host set to http://localhost:8472/api/
TrakHound Authentication API Host set to https://v1.trakhound.com/api/
Server Plugins --------------------------
9 Plugins Found
------------------------------
MTConnect Status : v1.5.9.23220
Snapshot Data : v1.5.9.23220
Parts : v1.5.9.23220
Overrides : v1.5.9.23220
OEE : v1.5.9.23220
MTConnect : v1.5.9.23220
Instances : v1.5.9.23220
GeneratedEvents : v1.5.9.23220
TrakHound Cloud : v1.5.9.23220
----------------------------------------
API Configuration File Monitor Started
API Configuration File Monitor Started

C:\Program Files (x86)\TrakHound\Server>net start TrakHound-Server
The service is not responding to the control function.

More help is available by typing NET HELPMSG 2186.
```

![image](https://user-images.githubusercontent.com/15605269/206564585-3958c9a0-3803-4d30-9ba3-b1c759327e33.png)
![image](https://user-images.githubusercontent.com/15605269/206564787-babc32ac-ff04-413e-a821-7247ed2cbb7e.png)
![image](https://user-images.githubusercontent.com/15605269/206565245-0f3819ef-7308-4aae-b520-da1d20f57a61.png)

**Comment by PatrickRitchie** [comment]
@skibum1869 Try running the exe from the command line using the "debug" argument as this may give you some insight into what is wrong:
```
trakhound-server debug
```

You may also want to try clearing the **C:\TrakHound\Backup** and **C:\TrakHound\Databases** directories.

Please let me know if you are still having issues after trying the above.

Thanks,
-Patrick

**Comment by skibum1869** [comment]
It appears to run from the command line. Is there a good way to uninstall and reinstall the server? ![image](https://user-images.githubusercontent.com/15605269/213213466-b014071c-ba3b-4a71-9bae-5b37a465f9b8.jpeg) ![Uploading 213213658...]

**Comment by mohitvashistha** [comment]
I faced the same issue, i fixed it by changing the logon account from system to this account.

![Image](https://github.com/user-attachments/assets/a879e3c4-6c17-4e1d-abac-cf95eac31e97)
